version: "3"

services:
  minidlna:
    image: vladgh/minidlna:latest
    container_name: minidlna
    network_mode: "host"
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=cassini_minidlna
    volumes:
      - /media/pi/FAST:/media
    restart: unless-stopped